# Generated by Django 4.0.1 on 2022-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
