# Generated by Django 4.0.1 on 2022-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='busy',
            field=models.CharField(choices=[('busy', 'busy'), ('available', 'available')], max_length=50, null=True),
        ),
    ]
