# Generated by Django 4.0.1 on 2022-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='busy',
            field=models.CharField(choices=[('busy', 'Busy'), ('available', 'Available')], max_length=50, null=True),
        ),
    ]
