# Generated by Django 4.0.1 on 2022-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='busy',
            field=models.CharField(choices=[('On Duty', 'On Duty'), ('Free', 'Free')], max_length=50, null=True),
        ),
    ]
