# Generated by Django 4.0.1 on 2022-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_district_profile_division_profile_thana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='busy',
            field=models.CharField(choices=[('কর্মরত আছে', 'কর্মরত আছে'), ('খালি আছে', 'খালি আছে')], max_length=50, null=True),
        ),
    ]
