# Generated by Django 3.2.4 on 2022-10-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thana',
        ),
        migrations.RemoveField(
            model_name='message',
            name='union',
        ),
        migrations.RemoveField(
            model_name='message',
            name='vilage',
        ),
    ]
