# Generated by Django 3.2.4 on 2022-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20221010_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('reciepient', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
