# Generated by Django 3.2.4 on 2022-11-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reciepient',
            new_name='reciepient_email',
        ),
    ]
