# Generated by Django 4.0.1 on 2022-09-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_rename_title_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='district',
        ),
        migrations.RemoveField(
            model_name='project',
            name='division',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thana',
        ),
    ]
