# Generated by Django 4.0.1 on 2022-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_remove_project_district_remove_project_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
