# Generated by Django 4.0.1 on 2022-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_project_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
