# Generated by Django 4.0.1 on 2022-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_project_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, choices=[('মানিকগঞ্জ', 'মানিকগঞ্জ'), ('টাঙ্গাইল', 'টাঙ্গাইল'), ('ফরিদপুর', 'ফরিদপুর'), ('গাজিপুর', 'গাজিপুর')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='division',
            field=models.CharField(blank=True, choices=[('ঢাকা', 'ঢাকা'), ('রাজশাহী', 'রাজশাহী'), ('যশোর', 'যশোর')], max_length=200),
        ),
    ]
