# Generated by Django 4.0.1 on 2022-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thana',
            field=models.CharField(blank=True, choices=[('মানিকগঞ্জ সদর', 'মানিকগঞ্জ সদর'), ('হরিরামপুর', 'হরিরামপুর'), ('শিবালয়', 'শিবালয়'), ('ঘিয়র', 'ঘিয়র'), ('সিংগাইর', 'সিংগাইর'), ('পাবনা সদর উপজেলা', 'পাবনা সদর উপজেলা'), ('বগুরা', 'বগুরা')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, choices=[('মানিকগঞ্জ', 'মানিকগঞ্জ'), ('টাঙ্গাইল', 'টাঙ্গাইল'), ('ফরিদপুর', 'ফরিদপুর'), ('গাজিপুর', 'গাজিপুর'), ('রাজবারি', 'রাজবারি'), ('পাবনা', 'পাবনা'), ('নাটোর', 'নাটোর'), ('চাপাইনবাবগঞ্জ', 'চাপাইনবাবগঞ্জ'), ('বগুরা', 'বগুরা')], max_length=200),
        ),
    ]
