# Generated by Django 4.0.1 on 2022-10-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_project_thana_alter_project_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sourch_link',
        ),
    ]
