# Generated by Django 3.2.4 on 2022-10-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_auto_20221010_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_tatal', 'title']},
        ),
    ]
